

exp="10*2+10";
console.log("Exception Handling");
try{
    const result = eval(exp);
    console.log(result);
    

}
catch{
    console.log("There are some issues in expression");
    
}
finally{

    console.log("Task completed");
    
}


